added hook useDocumentVisibility
Warckut/react-document-visibility pull request #1
Opened 2024-07-08 08:08 UTC by Warckut

2024-07-08 08:12 UTC, Warckut commented
@tvivls

2024-07-08 10:12 UTC, tvivls requested changes
1. сделай поддержку реакта от 16.8.0
2. используй eslint (без prettier).
3. если открыть вкладку, но не заходить на нее, пишет, что страница покинута 1 раз. Иногда такое же происходит при первом открытии вкладки.

на будущее: ВСЕ изменения должны проходить через ревью. в master ветке только пустой readme либо пустые файлы. Тут например я сейчас не вижу твой tsconfig

2024-07-08 10:12 UTC, tvivls commented on rollup.config.js
> +const packageJson = require('./package.json')
почему require, а не import?)

2024-07-08 10:12 UTC, tvivls commented on src/useDocumentVisibility/index.ts
я бы скорее назвала этот файл src/hooks/useDocumentVisibility.ts

2024-07-08 10:12 UTC, tvivls commented on src/useDocumentVisibility/index.ts
> +    const cb = () => {
что за `cb`?

2024-07-08 10:12 UTC, tvivls commented on src/useDocumentVisibility/index.ts
> +      if (!document.hidden) setCount((v) => v + 1);
`v` плохое название

2024-07-09 19:56 UTC, tvivls commented on src/useDocumentVisibility/index.ts
> +    return () => document.removeEventListener('visibilitychange', callback);
дублируешь 13-14 строки

2024-07-10 12:58 UTC, Warckut commented
@tvivls, исправил замечания

2024-07-10 13:55 UTC, Warckut commented
Вспомнил что использовал не тот config для eslint'а

2024-07-16 19:09 UTC, tvivls reviewed
я все равно ловлю баг, что `если открыть вкладку, но не заходить на нее, пишет, что страница покинута 1 раз`

2024-07-16 19:09 UTC, tvivls commented on src/hooks/useDocumentVisibility.ts
> +  const [listenersState, setListiners] = useState<Set<() => void>>(new Set());
вынеси в отдельный тип

2024-07-18 10:56 UTC, Warckut commented
@tvivls, исправлено

2024-07-18 11:11 UTC, tvivls approved these changes
молодец, все работает

2024-07-18 11:15 UTC, merged